language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
env:
    - CI=false
before_deploy:
    - npm install netlify-cli -g
    - npm run test:cov
    - npm run build
script:
    - npm install
after_script: # Upload coverage reports
    - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run test:push-report
deploy:
    provider: script
    script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
    skip_cleanup: true
on:
    branch: master
